### ISSUE TITLE
Processing enex files generates invalid windows file names

### ISSUE THREAD

**Issue by jht001** [akosbalasko/yarle#514]
It looks like Yarle is generating invalid windows file and directory names, and issuing confusing messages in the log.
In the example below (using Yarle 5.2.2 on Windows 10).  It looks like one of the resource files has an invalid for windows file name. There is an error message in the log, but the log also says at the end that the note was successfully converted.  It looks like there are several different error messages, perhaps caused by the same problem.  I included some examples below.

Windows has lots of file naming rules.  Microsoft summarizes them here:
https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file

```
Conversion started at Mon Sep 04 2023 16:49:33 GMT-1000 (Hawaii-Aleutian Standard Time)
Converting note "T"...
relative resource work dir: ./_resources/T.200.resources
absolute resource work dir: C:\Users\James Thompson\Downloads\test_jht_enex\notes\jht001's notebook\_resources\T.200.resources
Failed to convert note: T, {"errno":-4058,"syscall":"open","code":"ENOENT","path":"C:\\Users\\James Thompson\\Downloads\\test_jht_enex\\notes\\jht001's notebook\\_resources\\T.200.resources\\displays.htm?id=7JysbAyMDJyc"}
Conversion finished at Mon Sep 04 2023 16:49:33 GMT-1000 (Hawaii-Aleutian Standard Time)
Note "T" converted successfully in 0.064 seconds.
Notes processed: 2492
```

**Here is another example that has a different error message but might be caused the same problem?
The error message doesn't give much to go on.**
```
Conversion started at Mon Sep 04 2023 16:25:51 GMT-1000 (Hawaii-Aleutian Standard Time)
Converting note "FCPX Stabilizer 2.0 - Final Cut Pro X and Motion 5 Special Effects , Plugins, Transitions and Themes"...
relative resource work dir: ./_resources/FCPX_Stabilizer_2.0_-_Final_Cut_Pro_X_and_Motion_5_Special_Effects_,_Plugins,_Transitions_and_Themes.resources
absolute resource work dir: C:\Users\James Thompson\Downloads\test_jht_enex\notes\jht001's notebook\_resources\FCPX_Stabilizer_2.0_-_Final_Cut_Pro_X_and_Motion_5_Special_Effects_,_Plugins,_Transitions_and_Themes.resources
mediaReference src ./_resources/FCPX_Stabilizer_2.0_-_Final_Cut_Pro_X_and_Motion_5_Special_Effects_,_Plugins,_Transitions_and_Themes.resources/unknown_filename.png added
mediaReference src ./_resources/FCPX_Stabilizer_2.0_-_Final_Cut_Pro_X_and_Motion_5_Special_Effects_,_Plugins,_Transitions_and_Themes.resources/ProAnonymous-Store-Page-213x300.png added
mediaReference src ./_resources/FCPX_Stabilizer_2.0_-_Final_Cut_Pro_X_and_Motion_5_Special_Effects_,_Plugins,_Transitions_and_Themes.resources/final-cut-pro-x-plugin-fcpx-audio-tools-pixel-film.jpg added
mediaReference src ./_resources/FCPX_Stabilizer_2.0_-_Final_Cut_Pro_X_and_Motion_5_Special_Effects_,_Plugins,_Transitions_and_Themes.resources/FCPX-Disintegrate-Store-213x300.png added
mediaReference src ./_resources/FCPX_Stabilizer_2.0_-_Final_Cut_Pro_X_and_Motion_5_Special_Effects_,_Plugins,_Transitions_and_Themes.resources/effects1.png added
mediaReference src ./_resources/FCPX_Stabilizer_2.0_-_Final_Cut_Pro_X_and_Motion_5_Special_Effects_,_Plugins,_Transitions_and_Themes.resources/FCPX-PIP-2.jpg added
mediaReference src ./_resources/FCPX_Stabilizer_2.0_-_Final_Cut_Pro_X_and_Motion_5_Special_Effects_,_Plugins,_Transitions_and_Themes.resources/FCPX_Auto_Tracker_2_Store-213x300.png added
mediaReference src ./_resources/FCPX_Stabilizer_2.0_-_Final_Cut_Pro_X_and_Motion_5_Special_Effects_,_Plugins,_Transitions_and_Themes.resources/ProPuppet-Lite-Store-213x300.png added
Failed to convert note: FCPX Stabilizer 2.0 - Final Cut Pro X and Motion 5 Special Effects , Plugins, Transitions and Themes, {}
Conversion finished at Mon Sep 04 2023 16:25:51 GMT-1000 (Hawaii-Aleutian Standard Time)
Note "FCPX Stabilizer 2.0 - Final Cut Pro X and Motion 5 Special Effects , Plugins, Transitions and Themes" converted successfully in 0.135 seconds.
Notes processed: 292
```

**Another error message, probably from the same issue:**
```
Conversion started at Mon Sep 04 2023 16:24:30 GMT-1000 (Hawaii-Aleutian Standard Time)
Converting note "Hawaiian Sanctuary Retreat Center is an Eco Retreat nestled in the jungles of Big Island, Hawai’i. We are dedicated to providing accommodations, retreats, permaculture education as well as opportunities for personal and collective growth. We open our arms"...
relative resource work dir: ./_resources/Hawaiian_Sanctuary_Retreat_Center_is_an_Eco_Retreat_nestled_in_the_jungles_of_Big_Island,_Hawai’i._We_are_dedicated_to_providing_accommodations,_retreats,_permaculture_education_as_well_as_opportunities_for_personal_and_collective_growth._We_open_our_ar.resources
absolute resource work dir: C:\Users\James Thompson\Downloads\test_jht_enex\notes\jht001's notebook\_resources\Hawaiian_Sanctuary_Retreat_Center_is_an_Eco_Retreat_nestled_in_the_jungles_of_Big_Island,_Hawai’i._We_are_dedicated_to_providing_accommodations,_retreats,_permaculture_education_as_well_as_opportunities_for_personal_and_collective_growth._We_open_our_ar.resources
Failed to convert note: Hawaiian Sanctuary Retreat Center is an Eco Retreat nestled in the jungles of Big Island, Hawai’i. We are dedicated to providing accommodations, retreats, permaculture education as well as opportunities for personal and collective growth. We open our arms, {"errno":-4071,"syscall":"mkdir","code":"EINVAL","path":"C:\\Users\\James Thompson\\Downloads\\test_jht_enex\\notes\\jht001's notebook\\_resources\\Hawaiian_Sanctuary_Retreat_Center_is_an_Eco_Retreat_nestled_in_the_jungles_of_Big_Island,_Hawai’i._We_are_dedicated_to_providing_accommodations,_retreats,_permaculture_education_as_well_as_opportunities_for_personal_and_collective_growth._We_open_our_ar.resources"}
Conversion finished at Mon Sep 04 2023 16:24:30 GMT-1000 (Hawaii-Aleutian Standard Time)
Note "Hawaiian Sanctuary Retreat Center is an Eco Retreat nestled in the jungles of Big Island, Hawai’i. We are dedicated to providing accommodations, retreats, permaculture education as well as opportunities for personal and collective growth. We open our arms" converted successfully in 0.007 seconds.
Notes processed: 164
```

**Another one:**
```
Conversion started at Mon Sep 04 2023 16:23:14 GMT-1000 (Hawaii-Aleutian Standard Time)
Converting note "Soil, Watering, Fertilizer and questions for Al (tapla)"...
relative resource work dir: ./_resources/Soil,_Watering,_Fertilizer_and_questions_for_Al_(tapla).resources
absolute resource work dir: C:\Users\James Thompson\Downloads\test_jht_enex\notes\jht001's notebook\_resources\Soil,_Watering,_Fertilizer_and_questions_for_Al_(tapla).resources
Failed to convert note: Soil, Watering, Fertilizer and questions for Al (tapla), {"code":"ERR_INVALID_ARG_TYPE"}
Conversion finished at Mon Sep 04 2023 16:23:15 GMT-1000 (Hawaii-Aleutian Standard Time)
Note "Soil, Watering, Fertilizer and questions for Al (tapla)" converted successfully in 0.765 seconds.
Notes processed: 28

```

**Comment by akosbalasko** [comment]
Hi @jht001 ,
In version 5.5.0 I released a feature in the config in where you can set the specific characters to be replaced in the filenames. It is called: "replacementCharacterMap", with it's default settings it should resolve all of your filenames-related problems. 
So, my suggestion would be to use the latest version. 
And of course feel free to contact if you still face with issues. 
Thank you! 
Regards,
akos

**Comment by jht001** [comment]
Thanks for the quick response.  I'm sorry I typed in the wrong version number, The errors occurred with the latest version I just downloaded.  It would be helpful if the log included the Yarle version number.

The log shows:
   "replacementChar": "_",
    "replacementCharacterMap": {
        "<": "_",
        ">": "_",
        ":": "_",
        "\"": "_",
        "/": "_",
        "\\": "_",
        "|": "_",
        "?": "_",
        "*": "_"
    },

but I'm still getting the errors I mentioned.  It doesn't look like its doing the replacements in the resource file names.  Also, even though a number of note files did not get written, at the end of the log it says:
Conversion finished: 3566 succeeded, 0 skipped, 0 failed. Total notes: 3566
After the run in the output directory, there only 3498 note files.

**Comment by akosbalasko** [comment]
Hi @jht001 ,
Nope, I have test for doint the replacements in the resource file names also. So It looks like that something else is happening that results invalid file names. Maybe an other character that is missing from the config?

**Comment by jht001** [comment]
In the error message below it appears to be showing the file name with  a '?' in it, which is in the replacement list.

```
Failed to convert note: Zoiper WEB introduces communication functionality to any web application and VoI, {"errno":-4058,"syscall":"open","code":"ENOENT","path":"C:\\Users\\James Thompson\\Downloads\\test_jht_enex\\notes\\jht001's notebook\\_resources\\Zoiper_WEB_introduces_communication_functionality_to_any_web_application_and_VoI.resources\\aggbug.ashx?id=0e06604d-88cb-41aa-a54d-39d1012b2b84"}
```

**Comment by akosbalasko** [comment]
hm.. could you pls try to add "\?" instead of "?" in the config? 
thanks!

**Comment by jht001** [comment]
OK, trying that now

**Comment by jht001** [comment]
If I add a backslash, the "Start Conversion" button stops working.  I suspect there is an error parsing the replacement character configuration.  I tried several combinations of things, all worked until I add a backslash.

**Comment by akosbalasko** [comment]
@jht001 ehhh, I'm sorry, how about ```"\\?"``` ?

**Comment by jht001** [comment]
using "\\?" runs ok, but doesn't fix the error.
I've attached a test enex file with one note that causes the error.
[Zoiper WEB introduces communication functionality to any web application and VoI.zip](https://github.com/akosbalasko/yarle/files/12528672/Zoiper.WEB.introduces.communication.functionality.to.any.web.application.and.VoI.zip)

**Comment by akosbalasko** [comment]
@jht001 oookay, thank you! Now i get the point what was wrong: the character replacement was done on filenames only, but not on their extension. and as your resource looks like an html with some parameters, the question mark was after the dot, so it was recognized as the part of the extension. 
Now it is fixed in version 5.5.3.

Cheers,
akos

**Comment by jht001** [comment]
Thanks for the new version, it fixed many of the errors, but there are still some failing.  I've attached the enex files for the 3 different kinds of errors I'm still seeing.
Thanks.
[enex_error_examples.zip](https://github.com/akosbalasko/yarle/files/12541954/enex_error_examples.zip)

**Comment by akosbalasko** [comment]
Hi @jht001 ,
Thanks for checking! 

These 3 are webclips, so first of all, **don't forget to set Web clips to be converted (by default it is false)**. This skipping of Web clips could cause the misleading number of the processed files and the amount of files really converted.
  
I checked all of them, and they have different problems, one of them contains an image that has no data property (I don't know how Evernote missed it, anyway), which broke the line, it is fixed. 
The others' problems are related to their title length produced long-long files, which is maximized to 50 chars, but I missed to maximize it in the resource folder name. So I fixed it now. 

Please check the latest version (5.5.4), which contains the fixes.

**Comment by jht001** [comment]
Thanks for the warning about converting web clips not being the default.
I ran everything in my Evernote (over 4 thousand notes), and didn't see any error messages.
Thanks so much for fixing these issues!  Impressive support.

**Comment by akosbalasko** [comment]
@jht001 ,
It's great! Thanks for raising your issues and let me to improve Yarle! 
If you satisfied with the result, pls consider to give a star here on Github for Yarle, or if you can afford, to donate the project by inviting meg for some coffees here: https://www.buymeacoffee.com/akosbalasko

Thanks a lot, and enjoy your limitless freedom outside of Evernote!
